### ISSUE TITLE
Error on tests

### ISSUE THREAD

**Issue by simon-p-r** [dotnil/ssh-config#3]
I have tried running tests locally, however I have encountered this error

````JS
D:\Modules\ssh-config>npm test

> ssh-config@0.1.0 test D:\Modules\ssh-config
> mocha test/**/*.js



  glob
    V glob asterisk mark
    V glob question mark
    V glob pattern list
    V glob negated pattern list

  ssh-config
    V .parse ssh config text into object
    V .query ssh config by host
    1) .stringify the parsed object back to string


  6 passing (25ms)
  1 failing

  1) ssh-config .stringify the parsed object back to string:
     Error: expected 'ControlMaster auto\r\nControlPath ~/.ssh/master-%r@%h:%p\r\nServerAliveInterval 80\r\n\r\nHost tahoe1\r\n  HostName tahoe1.com\r\n  Compression yes\r\n\r\nHost tahoe2\r\n  HostName tahoe2.com\r\n  ServerAliveInterval 60\r\n\r\nHost *\r\n  IdentityFile ~/.ssh/id_rsa\r\n\r\nHost
tahoe?\r\n  User nil\r\n  ForwardAgent true\r\n  ProxyCommand ssh -q gateway -W %h:%p\r\n' to contain 'ControlMaster auto\nControlPath ~/.ssh/master-%r@%h:%p\nServerAliveInterval 80\n\nHost tahoe1\n  HostName tahoe1.com\n  Compression yes\n\nHost tahoe2\n  HostName tahoe2.com\n  ServerAliveInterval
60\n\nHost *\n  IdentityFile ~/.ssh/id_rsa\n\nHost tahoe?\n  User nil\n  ForwardAgent true\n  ProxyCommand ssh -q gateway -W %h:%p'
      at Assertion.assert (D:\Modules\ssh-config\node_modules\expect.js\index.js:96:13)
      at Assertion.string.Assertion.contain (D:\Modules\ssh-config\node_modules\expect.js\index.js:410:12)
      at Context.<anonymous> (D:\Modules\ssh-config\test\test.ssh-config.js:41:24)
      at callFn (D:\Modules\ssh-config\node_modules\mocha\lib\runnable.js:251:21)
      at Test.Runnable.run (D:\Modules\ssh-config\node_modules\mocha\lib\runnable.js:244:7)
      at Runner.runTest (D:\Modules\ssh-config\node_modules\mocha\lib\runner.js:374:10)
      at D:\Modules\ssh-config\node_modules\mocha\lib\runner.js:452:12
      at next (D:\Modules\ssh-config\node_modules\mocha\lib\runner.js:299:14)
      at D:\Modules\ssh-config\node_modules\mocha\lib\runner.js:309:7
      at next (D:\Modules\ssh-config\node_modules\mocha\lib\runner.js:248:23)
      at Immediate._onImmediate (D:\Modules\ssh-config\node_modules\mocha\lib\runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:367:17)



npm ERR! Test failed.  See above for more details.

D:\Modules\ssh-config> 
````

This happens on both branches (master and add query)

**Comment by dotnil** [comment]
Ah, it is caused by the different line ending Windows uses.

**Comment by simon-p-r** [comment]
Thanks when will you publish this branch to npm

**Comment by dotnil** [comment]
My colleague @jserme will review #2 tonight (GMT +8)

**Comment by simon-p-r** [comment]
OK thanks

**Comment by simon-p-r** [comment]
That has fixed issue with stringify test
